name: Publish Gem

on:
  push:
    branches: [ main ]
  # Allows use to run it manually
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
       - name: Checkout
         uses: actions/checkout@v2

       - name: Build and publish to RubyGems
         uses: actionshub/publish-gem-to-rubygems@main
         with:
           token: ${{ secrets.RUBYGEMS_API_KEY }}
