name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: test
      TZ: "Europe/Copenhagen"

    steps:
      - name: Remove Microsoft Error
        run: sudo rm /etc/apt/sources.list.d/microsoft-prod.list

      - name: Update apt-get
        run: sudo apt-get update

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Install required libraries
        run: sudo apt-get update -y && sudo apt-get install -y libsqlite3-dev

      - name: Install dependencies
        run: |
          bundle config unset deployment
          bundle install --jobs 4 --retry 3

      - name: Set up database
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run tests
        run: bundle exec rails test
